[package]
name = "pcr"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
rand = "0.9.2"
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
